Use SHA256 to calculate PCR bank hash
The PCR bank hash is used as the policy digest. Since SHA256 is chosen
as the hash algorithm of policy digest for 'StartAuthSession', we should
use the same hash algorithm to generate the PCR bank hash, not the hash
algorithm of the PCR bank.

Example:

 # pcr-oracle -A sha384 --input secret --output sealed --from current seal-secret 0,2,4,12
 # pcr-oracle -A sha384 --input sealed --output recovered unseal-secret 0,2,4,12
 ::: took 3.127 sec to create SRK
 WARNING:esys:src/tss2-esys/api/Esys_Unseal.c:295:Esys_Unseal_Finish() Received TPM Error
 ERROR:esys:src/tss2-esys/api/Esys_Unseal.c:98:Esys_Unseal() Esys Finish ErrorCode (0x0000099d)
 Error: Esys_Unseal failed: tpm:session(1):a policy check failed

When the user chose the SHA384 PCR bank to seal the key,
'__pcr_bank_hash()' returned a SHA384 digest as the policy digest.
However, when pcr-oracle tried to unseal the key, the TPM session
expected a SHA256 policy digest specified by 'StartAuthSession', and
this led to policy digest mismatch.

For simplicity, this commit makes '__pcr_bank_hash' stick to the hash
algorithm of 'StartAuthSession': SHA256.

Signed-off-by: Gary Lin <glin@suse.com>